name = "ssg-visitor-log"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Created by `npx wrangler kv namespace create VISITS` - paste the id it
# prints in place of the placeholder below.
kv_namespaces = [
  { binding = "VISITS", id = "0b3ef7fcb959481c8a0d868d0f9dabb4" }
]
